config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  namespace :admin do
    resources :charities
  end

  post 'donate', to: 'website#donate', as: 'donate'

  root to: 'website#index'

end

app/models/app.rb
class App
  def all_charities
    Charity.order(:created_at).all
  end

  def build_charity(attributes = {})
    # NOTE currency is for now fixed to THB.
    Charity.new(attributes.merge(total: 0, currency: "THB"))
  end

  def create_charity(attributes)
    charity = build_charity(attributes)
    charity.save
    charity
  end

  def count_charities
    Charity.count
  end

  def find_charity(id)
    Charity.find_by(id: id)
  end
end

app/models/charity.rb
class Charity < ActiveRecord::Base
  validates :name, presence: true

  def credit_amount(amount)
    update_attribute :total, (total + amount)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :recoverable, :rememberable, :trackable,
    :validatable
end

app/controllers/admin/charities_controller.rb
class Admin::CharitiesController < ApplicationController
  before_action :authenticate_user!
  def index
    @charities = @app.all_charities
  end

  def new
    @charity = @app.build_charity
  end

  def create
    @charity = @app.create_charity(charity_params)

    if @charity.persisted?
      flash.notice = t(".success")
      redirect_to admin_charities_path
    else
      flash.alert = t(".failure")
      render :new
    end
  end

  private

  def charity_params
    params.require(:charity).permit(:name, :description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_app

  private

  def set_app
    @app = App.new
  end
end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController
  before_action :find_charity, only: [:donate]

  def index
    @token = nil
  end

  def donate
    # OmiseCustom::Payment class for create a charge located at "lib/omise_custom/payment.rb"
    request = OmiseCustom::Payment.new(@charity, params[:omise_token], (params[:amount].to_i * 100), (params[:amount].to_i != 999), 'THB', "Donation to #{@charity.name} [#{@charity.id}]", Rails.env ).create
    if request == true
      redirect_to root_path, notice:  notice
    else
      redirect_to root_path, alert: "Minimum amount can allowed 0.2."
    end
  end

  private

  # retrieve_token.
  def retrieve_token(token)
    if Rails.env.test?
      OpenStruct.new({
        id: "tokn_X",
        card: OpenStruct.new({
          name: "J DOE",
          last_digits: "4242",
          expiration_month: 10,
          expiration_year: 2020,
          security_code_check: false,
        }),
      })
    else
      Omise::Token.retrieve(token)
    end
  end

  #if Find Charity if not found than redirect to same page back with message.
  def find_charity
    @charity = Charity.find_by(id: params[:charity])
    if !@charity.present?
      failure_redirection
    end
  end

  #if something went wrong than it will redirect and show message.
  def failure_redirection
    @token = nil
    flash.now.alert = t(".failure")
    redirect_to root_path, alert: alert
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def m(amount, currency)
    Money.new(amount, currency).format
  end
end

app/views/admin/charities/index.html.erb
<%= t(".title") %>

<ul>
  <% @charities.each do |charity| %>
    <li><%= charity.name %> (<%= m charity.total, charity.currency %>)</li>
  <% end %>
</ul>

<%= link_to t("admin.charities.new.link"), new_admin_charity_path %>

app/views/admin/charities/new.html.erb
<%= form_for [:admin, @charity] do |f| %>

  <h1><%= t(".title") %></h1>

  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tamboon</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/layouts/website.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tamboon</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <%= yield %>

    <%= javascript_include_tag "https://cdn.omise.co/omise.js" %>

    <%= javascript_tag do %>
      Omise.setPublicKey("<%= Omise.vault_key %>");
    <% end %>

  </body>
</html>

app/views/website/index.html.erb
<%= form_tag donate_path, id: "donate" do %>

  <p>Pick a charity:</p>

  <ul>
    <% @app.all_charities.each do |charity| %>
      <li>
        <%= radio_button_tag :charity, charity.id %>
        <%= label_tag "charity_#{charity.id}", charity.name %>
      </li>
    <% end %>
  </ul>

  <div>
    <%= label_tag :amount %><br>
    <%= number_field_tag :amount, 500 %> THB
  </div>

  <% if @token && @token.card.security_code_check %>

    <%= hidden_field_tag :omise_token, @token.id %>

    <div>
      Number<br>
      **** **** **** <%= @token.card.last_digits %>
    </div>

    <div>
      Name (as on card)<br>
      <%= @token.card.name %>
    </div>

    <div>
      Expires<br>
      <%= @token.card.expiration_month %> / <%= @token.card.expiration_year %>
    </div>

    <div>
      Security Code<br>
      ***
    </div>

    <%= link_to t("website.index.use_another_card"), root_path %>

  <% else %>

    <%= hidden_field_tag :omise_token %>

    <div>
      Number<br>
      <%= text_field_tag nil, nil, placeholder: "XXXX XXXX XXXX XXXX", data: { omise: "number" } %>
    </div>

    <div>
      Name (as on card)<br>
      <%= text_field_tag nil, nil, placeholder: "J DOE", data: { omise: "holder_name" } %>
    </div>

    <div>
      Expires<br>
      <%= text_field_tag nil, nil, size: 4, placeholder: "XX", data: { omise: "expiration_month" } %>
      /
      <%= text_field_tag nil, nil, size: 4, placeholder: "XX", data: { omise: "expiration_year" } %>
    </div>

    <div>
      Security Code<br>
      <%= text_field_tag nil, nil, size: 8, placeholder: "XXX", data: { omise: "security_code" } %>
    </div>

  <% end %>

  <div>
    <%= submit_tag t("website.donate.link") %>
    <span class="cc_error"></span>
  </div>

<% end %>